[package]
name = "hecto"
version = "0.1.0"
authors = ["Ozaki Yoichi <zak@inl.ics.keio.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
